## More Pandas Review

In [3]:
import pandas as pd

In [6]:
data = {
    "Name": [
        "Alice", "Bob", "Charlie", "Diana", "Ethan", "Fiona", "George", "Hannah", "Ian", "Julia"
    ],
    "Age": [24, 30, 22, 28, 35, 27, 29, 31, 26, 23],
    "City": [
        "New York", "Chicago", "Seattle", "Boston", "Austin", "San Diego", "Denver", "Miami", "Houston", "Portland"
    ],
    "Score": [88, 92, 95, 78, 85, 91, 89, 87, 93, 90]
}

df = pd.DataFrame(data)

print(df)

      Name  Age       City  Score
0    Alice   24   New York     88
1      Bob   30    Chicago     92
2  Charlie   22    Seattle     95
3    Diana   28     Boston     78
4    Ethan   35     Austin     85
5    Fiona   27  San Diego     91
6   George   29     Denver     89
7   Hannah   31      Miami     87
8      Ian   26    Houston     93
9    Julia   23   Portland     90

---

## Handy Things

### Select Columns

In [9]:
df[["Name", "Score"]]

      Name  Score
0    Alice     88
1      Bob     92
2  Charlie     95
3    Diana     78
4    Ethan     85
5    Fiona     91
6   George     89
7   Hannah     87
8      Ian     93
9    Julia     90

### Filter Rows

In [10]:
df[df["Score"] > 90]

      Name  Age       City  Score
1      Bob   30    Chicago     92
2  Charlie   22    Seattle     95
5    Fiona   27  San Diego     91
8      Ian   26    Houston     93

### Even More Logic

In [12]:
df[(df["Score"] > 90) & (df["Age"] < 30)]

      Name  Age       City  Score
2  Charlie   22    Seattle     95
5    Fiona   27  San Diego     91
8      Ian   26    Houston     93

### .iloc and .loc for row/column selection

- .loc -> label-based
- .iloc -> position-based

In [14]:
df.iloc[0:5] # first 5 rows

      Name  Age      City  Score
0    Alice   24  New York     88
1      Bob   30   Chicago     92
2  Charlie   22   Seattle     95
3    Diana   28    Boston     78
4    Ethan   35    Austin     85

In [15]:
df.loc[df.Age < 30]

      Name  Age       City  Score
0    Alice   24   New York     88
2  Charlie   22    Seattle     95
3    Diana   28     Boston     78
5    Fiona   27  San Diego     91
6   George   29     Denver     89
8      Ian   26    Houston     93
9    Julia   23   Portland     90

### Describe

In [17]:
# Instant stats summary like min, max, mean, std, etc.
df.describe()

             Age      Score
count  10.000000  10.000000
mean   27.500000  88.800000
std     3.979112   4.802777
min    22.000000  78.000000
25%    24.500000  87.250000
50%    27.500000  89.500000
75%    29.750000  91.750000
max    35.000000  95.000000

In [30]:
data = {
    "Name": [
        "Alice", "Bob", "Charlie", None, "Ethan",
        "Fiona", None, "Hannah", "Ian", "Julia"
    ],
    "Age": [24, 30, None, 28, 35, 27, 29, None, 26, 23],
    "City": [
        "New York", None, "Seattle", "Boston", "Austin",
        "San Diego", "Denver", None, "Houston", "Portland"
    ],
    "Score": [88, 92, 95, None, 85, 91, None, 87, 93, 90]
}

df = pd.DataFrame(data)
print(df)

# count all the null/empty
df["Score"].isnull().sum()

      Name   Age       City  Score
0    Alice  24.0   New York   88.0
1      Bob  30.0       None   92.0
2  Charlie   NaN    Seattle   95.0
3     None  28.0     Boston    NaN
4    Ethan  35.0     Austin   85.0
5    Fiona  27.0  San Diego   91.0
6     None  29.0     Denver    NaN
7   Hannah   NaN       None   87.0
8      Ian  26.0    Houston   93.0
9    Julia  23.0   Portland   90.0

np.int64(2)

In [35]:
data = {
    "Name": [
        "Alice", "Bob", "Charlie", None, "Ethan",
        "Fiona", None, "Hannah", "Ian", "Julia"
    ],
    "Age": [24, 30, None, 28, 35, 27, 29, None, 26, 23],
    "City": [
        "New York", None, "Seattle", "Boston", "Austin",
        "San Diego", "Denver", None, "Houston", "Portland"
    ],
    "Score": [88, 92, 95, None, 85, 91, None, 87, 93, 90]
}

df = pd.DataFrame(data)

# Fix/fill missing values (forward fill, etc.)
df["Score"].fillna(0)

0    88.0
1    92.0
2    95.0
3     0.0
4    85.0
5    91.0
6     0.0
7    87.0
8    93.0
9    90.0
Name: Score, dtype: float64

## Converting Types

Handy for cleaning real-world data!

In [45]:
data = {
    "Name": [
        "Alice", "Bob", "Charlie", "Diana", "Ethan", "Fiona", "George", "Hannah", "Ian", "Julia"
    ],
    "Age": [24, 30, 22, 28, 35, 27, 29, 31, 26, 23],
    "City": [
        "New York", "Chicago", "Seattle", "Boston", "Austin", "San Diego", "Denver", "Miami", "Houston", "Portland"
    ],
    "Score": [88, 92, 95, 78, 85, 91, 89, 87, 93, 90]
}

df = pd.DataFrame(data)

print(df)

print("type before conversion:", df["Score"].dtype)
df["Score"] = df["Score"].astype(float)
print("type after converstion:", df["Score"].dtype)

print(df)

      Name  Age       City  Score
0    Alice   24   New York     88
1      Bob   30    Chicago     92
2  Charlie   22    Seattle     95
3    Diana   28     Boston     78
4    Ethan   35     Austin     85
5    Fiona   27  San Diego     91
6   George   29     Denver     89
7   Hannah   31      Miami     87
8      Ian   26    Houston     93
9    Julia   23   Portland     90
type before conversion: int64
type after converstion: float64
      Name  Age       City  Score
0    Alice   24   New York   88.0
1      Bob   30    Chicago   92.0
2  Charlie   22    Seattle   95.0
3    Diana   28     Boston   78.0
4    Ethan   35     Austin   85.0
5    Fiona   27  San Diego   91.0
6   George   29     Denver   89.0
7   Hannah   31      Miami   87.0
8      Ian   26    Houston   93.0
9    Julia   23   Portland   90.0

## groupby() and aggregation

Notice how in this example, we group by Age and average the score! We can also do the same with City!

In [50]:
data = {
    "Name": [
        "Alice", "Bob", "Charlie", "Diana", "Ethan",
        "Fiona", "George", "Hannah", "Ian", "Julia",
        "Kevin", "Laura", "Mike", "Nina", "Oliver",
        "Paula", "Quinn", "Rachel", "Sam", "Tina"
    ],
    "Age": [
        24, 30, 22, 28, 35,
        27, 29, 31, 26, 23,
        24, 30, 22, 28, 35,
        27, 29, 31, 26, 23
    ],
    "City": [
        "New York", "Chicago", "Seattle", "Boston", "Austin",
        "San Diego", "Denver", "Miami", "Houston", "Portland",
        "New York", "Chicago", "Seattle", "Boston", "Austin",
        "San Diego", "Denver", "Miami", "Houston", "Portland"
    ],
    "Score": [
        88, 92, 95, 78, 85,
        91, 89, 87, 93, 90,
        86, 94, 96, 80, 84,
        89, 88, 86, 94, 92
    ]
}

df = pd.DataFrame(data)

print(df)

df.groupby("Age")["Score"].mean()

       Name  Age       City  Score
0     Alice   24   New York     88
1       Bob   30    Chicago     92
2   Charlie   22    Seattle     95
3     Diana   28     Boston     78
4     Ethan   35     Austin     85
5     Fiona   27  San Diego     91
6    George   29     Denver     89
7    Hannah   31      Miami     87
8       Ian   26    Houston     93
9     Julia   23   Portland     90
10    Kevin   24   New York     86
11    Laura   30    Chicago     94
12     Mike   22    Seattle     96
13     Nina   28     Boston     80
14   Oliver   35     Austin     84
15    Paula   27  San Diego     89
16    Quinn   29     Denver     88
17   Rachel   31      Miami     86
18      Sam   26    Houston     94
19     Tina   23   Portland     92

Age
22    95.5
23    91.0
24    87.0
26    93.5
27    90.0
28    79.0
29    88.5
30    93.0
31    86.5
35    84.5
Name: Score, dtype: float64

## Add new calculated columns

In [53]:
data = {
    "Name": [
        "Alice", "Bob", "Charlie", "Diana", "Ethan",
        "Fiona", "George", "Hannah", "Ian", "Julia",
        "Kevin", "Laura", "Mike", "Nina", "Oliver",
        "Paula", "Quinn", "Rachel", "Sam", "Tina"
    ],
    "Age": [
        24, 30, 22, 28, 35,
        27, 29, 31, 26, 23,
        24, 30, 22, 28, 35,
        27, 29, 31, 26, 23
    ],
    "City": [
        "New York", "Chicago", "Seattle", "Boston", "Austin",
        "San Diego", "Denver", "Miami", "Houston", "Portland",
        "New York", "Chicago", "Seattle", "Boston", "Austin",
        "San Diego", "Denver", "Miami", "Houston", "Portland"
    ],
    "Score": [
        88, 92, 95, 78, 85,
        91, 89, 87, 93, 90,
        86, 94, 96, 80, 84,
        89, 88, 86, 94, 92
    ]
}

df = pd.DataFrame(data)

print(df)

df["Genius?"] = df["Score"] > 90
print(df)

       Name  Age       City  Score
0     Alice   24   New York     88
1       Bob   30    Chicago     92
2   Charlie   22    Seattle     95
3     Diana   28     Boston     78
4     Ethan   35     Austin     85
5     Fiona   27  San Diego     91
6    George   29     Denver     89
7    Hannah   31      Miami     87
8       Ian   26    Houston     93
9     Julia   23   Portland     90
10    Kevin   24   New York     86
11    Laura   30    Chicago     94
12     Mike   22    Seattle     96
13     Nina   28     Boston     80
14   Oliver   35     Austin     84
15    Paula   27  San Diego     89
16    Quinn   29     Denver     88
17   Rachel   31      Miami     86
18      Sam   26    Houston     94
19     Tina   23   Portland     92
       Name  Age       City  Score  Genius?
0     Alice   24   New York     88    False
1       Bob   30    Chicago     92     True
2   Charlie   22    Seattle     95     True
3     Diana   28     Boston     78    False
4     Ethan   35     Austin     85    False
5     Fiona   27  San Diego     91     True
6    George   29     Denver     89    False
7    Hannah   31      Miami     87    False
8       Ian   26    Houston     93     True
9     Julia   23   Portland     90    False
10    Kevin   24   New York     86    False
11    Laura   30    Chicago     94     True
12     Mike   22    Seattle     96     True
13     Nina   28     Boston     80    False
14   Oliver   35     Austin     84    False
15    Paula   27  San Diego     89    False
16    Quinn   29     Denver     88    False
17   Rachel   31      Miami     86    False
18      Sam   26    Houston     94     True
19     Tina   23   Portland     92     True

## Sorting Data

Sort any column, descending or ascending

In [64]:
data = {
    "Name": [
        "Alice", "Bob", "Charlie", "Diana", "Ethan",
        "Fiona", "George", "Hannah", "Ian", "Julia",
        "Kevin", "Laura", "Mike", "Nina", "Oliver",
        "Paula", "Quinn", "Rachel", "Sam", "Tina"
    ],
    "Age": [
        24, 30, 22, 28, 35,
        27, 29, 31, 26, 23,
        24, 30, 22, 28, 35,
        27, 29, 31, 26, 23
    ],
    "City": [
        "New York", "Chicago", "Seattle", "Boston", "Austin",
        "San Diego", "Denver", "Miami", "Houston", "Portland",
        "New York", "Chicago", "Seattle", "Boston", "Austin",
        "San Diego", "Denver", "Miami", "Houston", "Portland"
    ],
    "Score": [
        88, 92, 95, 78, 85,
        91, 89, 87, 93, 90,
        86, 94, 96, 80, 84,
        89, 88, 86, 94, 92
    ]
}

df = pd.DataFrame(data)

# print(df)

df.sort_values("Age", ascending=True)
# print(df)

       Name  Age       City  Score
2   Charlie   22    Seattle     95
12     Mike   22    Seattle     96
9     Julia   23   Portland     90
19     Tina   23   Portland     92
10    Kevin   24   New York     86
0     Alice   24   New York     88
18      Sam   26    Houston     94
8       Ian   26    Houston     93
5     Fiona   27  San Diego     91
15    Paula   27  San Diego     89
3     Diana   28     Boston     78
13     Nina   28     Boston     80
6    George   29     Denver     89
16    Quinn   29     Denver     88
11    Laura   30    Chicago     94
1       Bob   30    Chicago     92
7    Hannah   31      Miami     87
17   Rachel   31      Miami     86
14   Oliver   35     Austin     84
4     Ethan   35     Austin     85

---

## Displaying Columns

In [65]:
data = {
    "Name": [
        "Alice", "Bob", "Charlie", "Diana", "Ethan",
        "Fiona", "George", "Hannah", "Ian", "Julia",
        "Kevin", "Laura", "Mike", "Nina", "Oliver",
        "Paula", "Quinn", "Rachel", "Sam", "Tina"
    ],
    "Age": [
        24, 30, 22, 28, 35,
        27, 29, 31, 26, 23,
        24, 30, 22, 28, 35,
        27, 29, 31, 26, 23
    ],
    "City": [
        "New York", "Chicago", "Seattle", "Boston", "Austin",
        "San Diego", "Denver", "Miami", "Houston", "Portland",
        "New York", "Chicago", "Seattle", "Boston", "Austin",
        "San Diego", "Denver", "Miami", "Houston", "Portland"
    ],
    "Score": [
        88, 92, 95, 78, 85,
        91, 89, 87, 93, 90,
        86, 94, 96, 80, 84,
        89, 88, 86, 94, 92
    ]
}

df = pd.DataFrame(data)

### List all column names

In [66]:
df.columns

Index(['Name', 'Age', 'City', 'Score'], dtype='object')

### Select specific columns

In [69]:
df[['Name', 'Age']].sort_values('Age')

       Name  Age
2   Charlie   22
12     Mike   22
9     Julia   23
19     Tina   23
10    Kevin   24
0     Alice   24
18      Sam   26
8       Ian   26
5     Fiona   27
15    Paula   27
3     Diana   28
13     Nina   28
6    George   29
16    Quinn   29
11    Laura   30
1       Bob   30
7    Hannah   31
17   Rachel   31
14   Oliver   35
4     Ethan   35

### Preview dataset including columns

Returns first 5 rows by default

In [70]:
df.head()

      Name  Age      City  Score
0    Alice   24  New York     88
1      Bob   30   Chicago     92
2  Charlie   22   Seattle     95
3    Diana   28    Boston     78
4    Ethan   35    Austin     85

---
## Selecting Rows with iloc

In [72]:
data = {
    "Name": [
        "Alice", "Bob", "Charlie", "Diana", "Ethan",
        "Fiona", "George", "Hannah", "Ian", "Julia",
        "Kevin", "Laura", "Mike", "Nina", "Oliver",
        "Paula", "Quinn", "Rachel", "Sam", "Tina"
    ],
    "Age": [
        24, 30, 22, 28, 35,
        27, 29, 31, 26, 23,
        24, 30, 22, 28, 35,
        27, 29, 31, 26, 23
    ],
    "City": [
        "New York", "Chicago", "Seattle", "Boston", "Austin",
        "San Diego", "Denver", "Miami", "Houston", "Portland",
        "New York", "Chicago", "Seattle", "Boston", "Austin",
        "San Diego", "Denver", "Miami", "Houston", "Portland"
    ],
    "Score": [
        88, 92, 95, 78, 85,
        91, 89, 87, 93, 90,
        86, 94, 96, 80, 84,
        89, 88, 86, 94, 92
    ]
}

df = pd.DataFrame(data)

### First row

In [73]:
df.iloc[0]

Name        Alice
Age            24
City     New York
Score          88
Name: 0, dtype: object

### First two rows

In [74]:
df.iloc[0:2]

    Name  Age      City  Score
0  Alice   24  New York     88
1    Bob   30   Chicago     92

### Every other row

In [75]:
df.iloc[::2]

       Name  Age      City  Score
0     Alice   24  New York     88
2   Charlie   22   Seattle     95
4     Ethan   35    Austin     85
6    George   29    Denver     89
8       Ian   26   Houston     93
10    Kevin   24  New York     86
12     Mike   22   Seattle     96
14   Oliver   35    Austin     84
16    Quinn   29    Denver     88
18      Sam   26   Houston     94

---
## Using Step (::) Slicing